.p2align 2,,3
.syntax unified
.text
wpad:
	.word 7681
	.word 559168
@ =78=
	.word 1
	.word 221708289
	.word 3383
	.word 4215474053
	.word 1925
	.word 113311161
	.word -1213
	.word 34602159
	.word -583
	.word 156043662
	.word 1728
	.word 4155244641
	.word -849
	.word 140118616
	.word 527
	.word 4205507872
	.word 2446
	.word 4146396509
	.word 2381
	.word 4092394234
	.word 97
	.word 72877826
	.word -2132
	.word 4137808968
	.word 2648
	.word 4173988205
	.word 2138
	.word 180424262
	.word -2784
	.word 57542881
	.word -1366
	.word 21689771
	.word -675
	.word 192804404
	.word -2268
	.word 34606457
	.word -1286
	.word 4180937430
	.word -3092
	.word 4256695927
	.word 1794
	.word 4071426551
	.word 1112
	.word 70781396
	.word -3000
	.word 4244769601
	.word -2399
	.word 13238515
	.word 365
	.word 4067101704
	.word -1846
	.word 4093574436
	.word 3654
	.word 4249552562
	.word 2753
	.word 161870540
	.word 2273
	.word 4172151451
	.word 878
	.word 45612257
	.word -2645
	.word 158857882
	.word 330
	.word 125105500
	.word -2508
	.word 4214553527
	.word 2941
	.word 121111078
	.word 3449
	.word 104269804
	.word 528
	.word 4161013664
	.word 2774
	.word 4267701727
	.word -1740
	.word 247727205
	.word 1655
	.word 4119329378
	.word -584
	.word 46396498
	.word 2551
	.word 4252503067
	.word -3411
	.word 4093310462
	.word 2516
	.word 92797294
	.word 1080
	.word 4106227148
	.word 2881
	.word 4116642847
	.word -766
	.word 4202693652
	.word 243
	.word 4095675164
	.word 202
	.word 4229298371
	.word 3080
	.word 4278126022
	.word -3477
	.word 4089121900
	.word -732
	.word 4046715526
	.word -3074
	.word 204862717
	.word 1714
	.word 80016893
	.word -693
	.word 4171429363
	.word -3380
	.word 201454098
	.word 2469
	.word 75696344
	.word -1381
	.word 4086039408
	.word -1875
	.word 14414419
	.word -799
	.word 4281992755
	.word 695
	.word 190117873
	.word -1382
	.word 4187948808
	.word 2423
	.word 4164158309
	.word -2724
	.word 4268428113
	.word 1908
	.word 251461951
	.word -1097
	.word 44172379
	.word -1228
	.word 4253093168
	.word 550
	.word 4215606040
	.word 1848
	.word 4043897008
	.word 2028
	.word 4110746135
	.word 1591
	.word 4049142381
	.word 1952
	.word 180882376
	.word -2044
	.word 4147444724
	.word -2593
	.word 4178903153
	.word -417
	.word 77924761
	.word 1125
	.word 212274354
	.word 3780
	.word 4170707275
	.word -1438
	.word 14352266
	.word -2681
	.word 4111142096
	.word -2990
	.word 228327089
	.word 707
	.word 4246602057
	.word 3099
	.word 4257545704
	.word -648
	.word 4116968974
	.word -2562
	.word 209319551
	.word -3078
	.word 113051485
	.word -1682
	.word 4218292571
	.word 1415
	.word 4182443759
	.word 3532
	.word 4196730489
	.word -2880
	.word 162596926
	.word -993
	.word 134349593
	.word -2722
	.word 4178114614
	.word 1044
	.word 202308173
	.word -1408
	.word 205589103
	.word 2844
	.word 4203737569
	.word -3041
	.word 4238868591
	.word -1853
	.word 4159507335
	.word -1003
	.word 4280808255
	.word 1478
	.word 4163827884
	.word -257
	.word 131922738
	.word 3180
	.word 4272294846
	.word -3141
	.word 143985349
	.word -1402
	.word 235074493
	.word -3789
	.word 4152822084
	.word -2819
	.word 4202825639
	.word 3125
	.word 4109041368
	.word -2563
	.word 4261870551
	.word 1220
	.word 94175934
	.word -2573
	.word 204536590
	.word -1886
	.word 4259510147
	.word -3566
	.word 4227201941
	.word 3073
	.word 4098683524
	.word 2264
	.word 4072602455
	.word 1155
	.word 201916510
	.word 880
	.word 4140495499
	.word -3188
	.word 21099670
	.word -3501
	.word 4282846830
	.word 219
	.word 4111595912
	.word 1587
	.word 50069091
	.word -198
	.word 111677143
	.word -2063
	.word 43846252
	.word 2900
	.word 4125750655
	.word 1800
	.word 110360656
	.word -1633
	.word 4189714813
	.word 869
	.word 129698619
	.word -1996
	.word 4281856470
	.word 2897
	.word 4268886227
	.word -405
	.word 127796329
	.word 319
	.word 105181734
	.word 3837
	.word 4290906423
@ =56=
	.word 1
	.word 221708289
	.word 3383
	.word 4215474053
	.word 1925
	.word 113311161
	.word -1213
	.word 34602159
	.word -583
	.word 156043662
	.word 1728
	.word 4155244641
	.word -849
	.word 140118616
	.word 527
	.word 4205507872
	.word 2446
	.word 4146396509
	.word 2381
	.word 4092394234
	.word 97
	.word 72877826
	.word -2132
	.word 4137808968
	.word 2648
	.word 4173988205
	.word 2138
	.word 180424262
	.word -2784
	.word 57542881
	.word -1366
	.word 21689771
	.word -675
	.word 192804404
	.word -2268
	.word 34606457
	.word -1286
	.word 4180937430
	.word -3092
	.word 4256695927
	.word 1794
	.word 4071426551
	.word 1112
	.word 70781396
	.word -3000
	.word 4244769601
	.word -2399
	.word 13238515
	.word 365
	.word 4067101704
	.word -1846
	.word 4093574436
	.word 3654
	.word 4249552562
	.word 2753
	.word 161870540
	.word 2273
	.word 4172151451
	.word 878
	.word 45612257
	.word -2645
	.word 158857882
	.word 330
	.word 125105500
@ =34=
	.word 1
	.word 221708289
	.word 3383
	.word 4215474053
	.word 1925
	.word 113311161
	.word -1213
	.word 34602159
	.word -583
	.word 156043662
	.word 1728
	.word 4155244641
	.word -849
	.word 140118616
	.word 527
	.word 4205507872
@ =012=
	.word 3383
	.word 4215474053
// void intt1024_16bit (int *v);
.global intt1024_16bit
.type intt1024_16bit, %function
intt1024_16bit:
	push {r4-r11, lr}
	adr.w r10, wpad
	ldm r10!, {r11-r12}
	vmov.w s0, r0
	add.w lr, r0, #2048
@ degree = 2
	vmov.w r0, s0
intt2_layer_7_8:
	ldr.w r9, [r10, #4]
	ldr.w r8, [r10], #8
	ldr.w r1, [r0]
	ldr.w r2, [r0, #4]
	ldr.w r3, [r0, #8]
	ldr.w r4, [r0, #12]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #4]
	str.w r3, [r0, #8]
	str.w r4, [r0, #12]
	str.w r1, [r0], #16
	cmp.w r0, lr
	bne.w intt2_layer_7_8
@ degree = 8
	vmov.w r0, s0
intt2_layer_5_6:
	ldr.w r9, [r10, #4]
	ldr.w r8, [r10], #8
	ldr.w r1, [r0]
	ldr.w r2, [r0, #16]
	ldr.w r3, [r0, #32]
	ldr.w r4, [r0, #48]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #16]
	str.w r3, [r0, #32]
	str.w r4, [r0, #48]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #16]
	ldr.w r3, [r0, #32]
	ldr.w r4, [r0, #48]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #16]
	str.w r3, [r0, #32]
	str.w r4, [r0, #48]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #16]
	ldr.w r3, [r0, #32]
	ldr.w r4, [r0, #48]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #16]
	str.w r3, [r0, #32]
	str.w r4, [r0, #48]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #16]
	ldr.w r3, [r0, #32]
	ldr.w r4, [r0, #48]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #16]
	str.w r3, [r0, #32]
	str.w r4, [r0, #48]
	str.w r1, [r0], #52
	cmp.w r0, lr
	bne.w intt2_layer_5_6
@ degree = 32
	vmov.w r0, s0
intt2_layer_3_4:
	ldr.w r9, [r10, #4]
	ldr.w r8, [r10], #8
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #4
	ldr.w r1, [r0]
	ldr.w r2, [r0, #64]
	ldr.w r3, [r0, #128]
	ldr.w r4, [r0, #192]
	ssub16.w r6, r1, r2
	sadd16.w r1, r1, r2
	smulbb r2, r9, r6
	smulbt r6, r9, r6
	smmulr r7, r2, r12
	mls r2, r7, r11, r2
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r2, r2, r6, lsl #16
	ssub16.w r6, r3, r4
	sadd16.w r3, r3, r4
	smultb r4, r9, r6
	smultt r6, r9, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
	ssub16.w r6, r1, r3
	sadd16.w r1, r1, r3
	smulbb r3, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r3, r12
	mls r3, r7, r11, r3
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r3, r3, r6, lsl #16
	ssub16.w r6, r2, r4
	sadd16.w r2, r2, r4
	smulbb r4, r8, r6
	smulbt r6, r8, r6
	smmulr r7, r4, r12
	mls r4, r7, r11, r4
	smmulr r7, r6, r12
	mls r6, r7, r11, r6
	pkhbt r4, r4, r6, lsl #16
@ reduce layer
	movw.w r5, #32768
	smlawb.w r7, r12, r1, r5
	smlawt.w r6, r12, r1, r5
	smulbt.w r7, r11, r7
	smulbt.w r6, r11, r6
	pkhbt.w r7, r7, r6, LSL #16
	ssub16.w r1, r1, r7
	str.w r2, [r0, #64]
	str.w r3, [r0, #128]
	str.w r4, [r0, #192]
	str.w r1, [r0], #196
	cmp.w r0, lr
	bne.w intt2_layer_3_4
	vmov.w r0, s0
	ldr.w r2, [r10, #4]
	ldr.w r1, [r10], #8
	vmov s4, s5, r1, r2
	add.w lr, r0, #256 @ 128
	vmov.w s3, lr
intt2_layer_0_1_2:
	vmov.w r1, r2, s4, s5
	ldr.w r7, [r0, #1024]
	ldr.w r8, [r0, #1280]
	ldr.w r9, [r0, #1536]
	ldr.w r10, [r0, #1792]
	ssub16.w r5, r7, r8
	sadd16.w r7, r7, r8
	smulbb r8, r2, r5
	smulbt r5, r2, r5
	smmulr r6, r8, r12
	mls r8, r6, r11, r8
	smmulr r6, r5, r12
	mls r5, r6, r11, r5
	pkhbt r8, r8, r5, lsl #16
	ssub16.w r5, r9, r10
	sadd16.w r9, r9, r10
	smultb r10, r2, r5
	smultt r5, r2, r5
	smmulr r6, r10, r12
	mls r10, r6, r11, r10
	smmulr r6, r5, r12
	mls r5, r6, r11, r5
	pkhbt r10, r10, r5, lsl #16
	ssub16.w r5, r7, r9
	sadd16.w r7, r7, r9
	smulbb r9, r1, r5
	smulbt r5, r1, r5
	smmulr r6, r9, r12
	mls r9, r6, r11, r9
	smmulr r6, r5, r12
	mls r5, r6, r11, r5
	pkhbt r9, r9, r5, lsl #16
	ssub16.w r5, r8, r10
	sadd16.w r8, r8, r10
	smulbb r10, r1, r5
	smulbt r5, r1, r5
	smmulr r6, r10, r12
	mls r10, r6, r11, r10
	smmulr r6, r5, r12
	mls r5, r6, r11, r5
	pkhbt r10, r10, r5, lsl #16
	ldr.w r2, [r0]
	ldr.w r3, [r0, #256]
	ldr.w r4, [r0, #512]
	ldr.w r5, [r0, #768]
	ssub16.w r6, r4, r5
	sadd16.w r4, r4, r5
	smulbb r5, r1, r6
	smulbt r6, r1, r6
	smmulr r1, r5, r12
	mls r5, r1, r11, r5
	smmulr r1, r6, r12
	mls r6, r1, r11, r6
	pkhbt r5, r5, r6, lsl #16
	sadd16.w r1, r2, r3
	ssub16.w r3, r2, r3
	sadd16.w r2, r1, r4
	ssub16.w r4, r1, r4
	sadd16.w r1, r3, r5
	ssub16.w r5, r3, r5
@reduction:
	movw.w lr, #32768
	smlawb.w r3, r12, r2, lr
	smlawt.w r6, r12, r2, lr
	smulbt.w r3, r11, r3
	smulbt.w r6, r11, r6
	pkhbt.w r3, r3, r6, LSL #16
	ssub16.w r2, r2, r3
	smlawb.w r3, r12, r7, lr
	smlawt.w r6, r12, r7, lr
	smulbt.w r3, r11, r3
	smulbt.w r6, r11, r6
	pkhbt.w r3, r3, r6, LSL #16
	ssub16.w r7, r7, r3
	@ layer 0
	sadd16.w r6, r5, r10
	ssub16.w r10, r5, r10
	sadd16.w r5, r4, r9
	ssub16.w r9, r4, r9
	sadd16.w r4, r1, r8
	ssub16.w r8, r1, r8
	sadd16.w r3, r2, r7
	ssub16.w r7, r2, r7
	str.w r4, [r0, #256]
	str.w r5, [r0, #512]
	str.w r6, [r0, #768]
	str.w r7, [r0, #1024]
	str.w r8, [r0, #1280]
	str.w r9, [r0, #1536]
	str.w r10, [r0, #1792]
	str.w r3, [r0], #4
	vmov.w lr, s3
	cmp.w r0, lr
	bne.w intt2_layer_0_1_2
	pop {r4-r11, pc}
