.p2align
.syntax unified
.text
.global good_mask_41_7_4_512
.type good_mask_41_7_4_512, %function
good_mask_41_7_4_512:
	push {r4-r11, lr}
	mov.w r2, #0
	ldr.w r3, [r1, #0]
	ldr.w r4, [r1, #4]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #984]
	ldr.w r4, [r1, #988]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #656]
	ldr.w r4, [r1, #660]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #328]
	ldr.w r4, [r1, #332]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #336]
	ldr.w r4, [r1, #340]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #8]
	ldr.w r4, [r1, #12]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #992]
	ldr.w r4, [r1, #996]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #664]
	ldr.w r4, [r1, #668]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #672]
	ldr.w r4, [r1, #676]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #344]
	ldr.w r4, [r1, #348]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #16]
	ldr.w r4, [r1, #20]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #1000]
	ldr.w r4, [r1, #1004]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #1008]
	ldr.w r4, [r1, #1012]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #680]
	ldr.w r4, [r1, #684]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #352]
	ldr.w r4, [r1, #356]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #24]
	ldr.w r4, [r1, #28]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #1016]
	ldr.w r4, [r1, #1020]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #688]
	ldr.w r4, [r1, #692]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #360]
	ldr.w r4, [r1, #364]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #32]
	ldr.w r4, [r1, #36]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #696]
	ldr.w r4, [r1, #700]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #368]
	ldr.w r4, [r1, #372]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #40]
	ldr.w r4, [r1, #44]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #704]
	ldr.w r4, [r1, #708]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #376]
	ldr.w r4, [r1, #380]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #48]
	ldr.w r4, [r1, #52]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #56]
	ldr.w r4, [r1, #60]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #712]
	ldr.w r4, [r1, #716]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #384]
	ldr.w r4, [r1, #388]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #392]
	ldr.w r4, [r1, #396]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #64]
	ldr.w r4, [r1, #68]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #720]
	ldr.w r4, [r1, #724]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #728]
	ldr.w r4, [r1, #732]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #400]
	ldr.w r4, [r1, #404]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #72]
	ldr.w r4, [r1, #76]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #736]
	ldr.w r4, [r1, #740]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #408]
	ldr.w r4, [r1, #412]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #80]
	ldr.w r4, [r1, #84]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #744]
	ldr.w r4, [r1, #748]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #416]
	ldr.w r4, [r1, #420]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #88]
	ldr.w r4, [r1, #92]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #752]
	ldr.w r4, [r1, #756]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #424]
	ldr.w r4, [r1, #428]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #96]
	ldr.w r4, [r1, #100]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #760]
	ldr.w r4, [r1, #764]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #432]
	ldr.w r4, [r1, #436]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #104]
	ldr.w r4, [r1, #108]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #112]
	ldr.w r4, [r1, #116]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #768]
	ldr.w r4, [r1, #772]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #440]
	ldr.w r4, [r1, #444]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #448]
	ldr.w r4, [r1, #452]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #120]
	ldr.w r4, [r1, #124]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #776]
	ldr.w r4, [r1, #780]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #784]
	ldr.w r4, [r1, #788]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #456]
	ldr.w r4, [r1, #460]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #128]
	ldr.w r4, [r1, #132]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #792]
	ldr.w r4, [r1, #796]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #464]
	ldr.w r4, [r1, #468]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #136]
	ldr.w r4, [r1, #140]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #800]
	ldr.w r4, [r1, #804]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #472]
	ldr.w r4, [r1, #476]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #144]
	ldr.w r4, [r1, #148]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #808]
	ldr.w r4, [r1, #812]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #480]
	ldr.w r4, [r1, #484]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #152]
	ldr.w r4, [r1, #156]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #816]
	ldr.w r4, [r1, #820]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #488]
	ldr.w r4, [r1, #492]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #160]
	ldr.w r4, [r1, #164]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #168]
	ldr.w r4, [r1, #172]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #824]
	ldr.w r4, [r1, #828]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #496]
	ldr.w r4, [r1, #500]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #504]
	ldr.w r4, [r1, #508]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #176]
	ldr.w r4, [r1, #180]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #832]
	ldr.w r4, [r1, #836]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #840]
	ldr.w r4, [r1, #844]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #512]
	ldr.w r4, [r1, #516]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #184]
	ldr.w r4, [r1, #188]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #848]
	ldr.w r4, [r1, #852]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #520]
	ldr.w r4, [r1, #524]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #192]
	ldr.w r4, [r1, #196]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #856]
	ldr.w r4, [r1, #860]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #528]
	ldr.w r4, [r1, #532]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #200]
	ldr.w r4, [r1, #204]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #864]
	ldr.w r4, [r1, #868]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #536]
	ldr.w r4, [r1, #540]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #208]
	ldr.w r4, [r1, #212]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #872]
	ldr.w r4, [r1, #876]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #544]
	ldr.w r4, [r1, #548]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #216]
	ldr.w r4, [r1, #220]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #224]
	ldr.w r4, [r1, #228]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #880]
	ldr.w r4, [r1, #884]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #552]
	ldr.w r4, [r1, #556]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #560]
	ldr.w r4, [r1, #564]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #232]
	ldr.w r4, [r1, #236]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #888]
	ldr.w r4, [r1, #892]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #896]
	ldr.w r4, [r1, #900]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #568]
	ldr.w r4, [r1, #572]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #240]
	ldr.w r4, [r1, #244]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #904]
	ldr.w r4, [r1, #908]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #576]
	ldr.w r4, [r1, #580]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #248]
	ldr.w r4, [r1, #252]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #912]
	ldr.w r4, [r1, #916]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #584]
	ldr.w r4, [r1, #588]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #256]
	ldr.w r4, [r1, #260]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #920]
	ldr.w r4, [r1, #924]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #592]
	ldr.w r4, [r1, #596]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #264]
	ldr.w r4, [r1, #268]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #928]
	ldr.w r4, [r1, #932]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #600]
	ldr.w r4, [r1, #604]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #272]
	ldr.w r4, [r1, #276]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #280]
	ldr.w r4, [r1, #284]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #936]
	ldr.w r4, [r1, #940]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #608]
	ldr.w r4, [r1, #612]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #616]
	ldr.w r4, [r1, #620]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #288]
	ldr.w r4, [r1, #292]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #944]
	ldr.w r4, [r1, #948]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #952]
	ldr.w r4, [r1, #956]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #624]
	ldr.w r4, [r1, #628]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #296]
	ldr.w r4, [r1, #300]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #960]
	ldr.w r4, [r1, #964]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #632]
	ldr.w r4, [r1, #636]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #304]
	ldr.w r4, [r1, #308]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #968]
	ldr.w r4, [r1, #972]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #640]
	ldr.w r4, [r1, #644]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #312]
	ldr.w r4, [r1, #316]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #976]
	ldr.w r4, [r1, #980]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #648]
	ldr.w r4, [r1, #652]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #320]
	ldr.w r4, [r1, #324]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	pop {r4-r11, pc}

.global good_mask_41_7_4_512x
.type good_mask_41_7_4_512x, %function
good_mask_41_7_4_512x:
	push {r4-r11, lr}
	mov.w r2, #0
	ldrh.w r3, [r1], #-2
    lsl.w r3, #16
	ldr.w r4, [r1, #4]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #984]
	ldr.w r4, [r1, #988]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #656]
	ldr.w r4, [r1, #660]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #328]
	ldr.w r4, [r1, #332]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #336]
	ldr.w r4, [r1, #340]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #8]
	ldr.w r4, [r1, #12]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #992]
	ldr.w r4, [r1, #996]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #664]
	ldr.w r4, [r1, #668]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #672]
	ldr.w r4, [r1, #676]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #344]
	ldr.w r4, [r1, #348]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #16]
	ldr.w r4, [r1, #20]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #1000]
	ldr.w r4, [r1, #1004]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #1008]
	ldr.w r4, [r1, #1012]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #680]
	ldr.w r4, [r1, #684]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #352]
	ldr.w r4, [r1, #356]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #24]
	ldr.w r4, [r1, #28]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #1016]
	ldr.w r4, [r1, #1020]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #688]
	ldr.w r4, [r1, #692]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #360]
	ldr.w r4, [r1, #364]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #32]
	ldr.w r4, [r1, #36]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldrh.w r3, [r1, #1024]
	str.w r2, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #696]
	ldr.w r4, [r1, #700]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #368]
	ldr.w r4, [r1, #372]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #40]
	ldr.w r4, [r1, #44]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #704]
	ldr.w r4, [r1, #708]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #376]
	ldr.w r4, [r1, #380]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #48]
	ldr.w r4, [r1, #52]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #56]
	ldr.w r4, [r1, #60]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #712]
	ldr.w r4, [r1, #716]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #384]
	ldr.w r4, [r1, #388]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #392]
	ldr.w r4, [r1, #396]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #64]
	ldr.w r4, [r1, #68]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #720]
	ldr.w r4, [r1, #724]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #728]
	ldr.w r4, [r1, #732]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #400]
	ldr.w r4, [r1, #404]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #72]
	ldr.w r4, [r1, #76]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #736]
	ldr.w r4, [r1, #740]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #408]
	ldr.w r4, [r1, #412]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #80]
	ldr.w r4, [r1, #84]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #744]
	ldr.w r4, [r1, #748]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #416]
	ldr.w r4, [r1, #420]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #88]
	ldr.w r4, [r1, #92]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #752]
	ldr.w r4, [r1, #756]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #424]
	ldr.w r4, [r1, #428]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #96]
	ldr.w r4, [r1, #100]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #760]
	ldr.w r4, [r1, #764]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #432]
	ldr.w r4, [r1, #436]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #104]
	ldr.w r4, [r1, #108]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #112]
	ldr.w r4, [r1, #116]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #768]
	ldr.w r4, [r1, #772]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #440]
	ldr.w r4, [r1, #444]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #448]
	ldr.w r4, [r1, #452]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #120]
	ldr.w r4, [r1, #124]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #776]
	ldr.w r4, [r1, #780]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #784]
	ldr.w r4, [r1, #788]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #456]
	ldr.w r4, [r1, #460]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #128]
	ldr.w r4, [r1, #132]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #792]
	ldr.w r4, [r1, #796]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #464]
	ldr.w r4, [r1, #468]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #136]
	ldr.w r4, [r1, #140]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #800]
	ldr.w r4, [r1, #804]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #472]
	ldr.w r4, [r1, #476]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #144]
	ldr.w r4, [r1, #148]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #808]
	ldr.w r4, [r1, #812]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #480]
	ldr.w r4, [r1, #484]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #152]
	ldr.w r4, [r1, #156]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #816]
	ldr.w r4, [r1, #820]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #488]
	ldr.w r4, [r1, #492]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #160]
	ldr.w r4, [r1, #164]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #168]
	ldr.w r4, [r1, #172]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #824]
	ldr.w r4, [r1, #828]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #496]
	ldr.w r4, [r1, #500]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #504]
	ldr.w r4, [r1, #508]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #176]
	ldr.w r4, [r1, #180]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #832]
	ldr.w r4, [r1, #836]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #840]
	ldr.w r4, [r1, #844]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #512]
	ldr.w r4, [r1, #516]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #184]
	ldr.w r4, [r1, #188]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #848]
	ldr.w r4, [r1, #852]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #520]
	ldr.w r4, [r1, #524]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #192]
	ldr.w r4, [r1, #196]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #856]
	ldr.w r4, [r1, #860]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #528]
	ldr.w r4, [r1, #532]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #200]
	ldr.w r4, [r1, #204]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #864]
	ldr.w r4, [r1, #868]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #536]
	ldr.w r4, [r1, #540]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #208]
	ldr.w r4, [r1, #212]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #872]
	ldr.w r4, [r1, #876]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #544]
	ldr.w r4, [r1, #548]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #216]
	ldr.w r4, [r1, #220]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #224]
	ldr.w r4, [r1, #228]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #880]
	ldr.w r4, [r1, #884]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #552]
	ldr.w r4, [r1, #556]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #560]
	ldr.w r4, [r1, #564]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #232]
	ldr.w r4, [r1, #236]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #888]
	ldr.w r4, [r1, #892]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #896]
	ldr.w r4, [r1, #900]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #568]
	ldr.w r4, [r1, #572]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #240]
	ldr.w r4, [r1, #244]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #904]
	ldr.w r4, [r1, #908]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #576]
	ldr.w r4, [r1, #580]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #248]
	ldr.w r4, [r1, #252]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #912]
	ldr.w r4, [r1, #916]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #584]
	ldr.w r4, [r1, #588]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #256]
	ldr.w r4, [r1, #260]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #920]
	ldr.w r4, [r1, #924]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #592]
	ldr.w r4, [r1, #596]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #264]
	ldr.w r4, [r1, #268]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #928]
	ldr.w r4, [r1, #932]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #600]
	ldr.w r4, [r1, #604]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #272]
	ldr.w r4, [r1, #276]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #280]
	ldr.w r4, [r1, #284]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #936]
	ldr.w r4, [r1, #940]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #608]
	ldr.w r4, [r1, #612]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #616]
	ldr.w r4, [r1, #620]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #288]
	ldr.w r4, [r1, #292]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #944]
	ldr.w r4, [r1, #948]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #952]
	ldr.w r4, [r1, #956]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #624]
	ldr.w r4, [r1, #628]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #296]
	ldr.w r4, [r1, #300]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #960]
	ldr.w r4, [r1, #964]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #632]
	ldr.w r4, [r1, #636]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #304]
	ldr.w r4, [r1, #308]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #968]
	ldr.w r4, [r1, #972]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #640]
	ldr.w r4, [r1, #644]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #312]
	ldr.w r4, [r1, #316]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	ldr.w r3, [r1, #976]
	ldr.w r4, [r1, #980]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #648]
	ldr.w r4, [r1, #652]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	ldr.w r3, [r1, #320]
	ldr.w r4, [r1, #324]
	str.w r4, [r0, #4]
	str.w r3, [r0], #8
	str.w r2, [r0, #4]
	str.w r2, [r0], #8
	pop {r4-r11, pc}

.global inv_good_mask_41_7_4_1148
.type inv_good_mask_41_7_4_1148, %function
inv_good_mask_41_7_4_1148:
	push {r4-r11, lr}
	mov.w r10, #5149
	movw.w r11, #44798
	movt.w r11, #12
	mov.w r12, #5167
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #0]
	str.w r3, [r0, #4]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1968]
	str.w r3, [r0, #1972]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1640]
	str.w r3, [r0, #1644]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1312]
	str.w r3, [r0, #1316]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #984]
	str.w r3, [r0, #988]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #656]
	str.w r3, [r0, #660]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #328]
	str.w r3, [r0, #332]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #336]
	str.w r3, [r0, #340]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #8]
	str.w r3, [r0, #12]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1976]
	str.w r3, [r0, #1980]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1648]
	str.w r3, [r0, #1652]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1320]
	str.w r3, [r0, #1324]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #992]
	str.w r3, [r0, #996]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #664]
	str.w r3, [r0, #668]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #672]
	str.w r3, [r0, #676]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #344]
	str.w r3, [r0, #348]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #16]
	str.w r3, [r0, #20]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1984]
	str.w r3, [r0, #1988]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1656]
	str.w r3, [r0, #1660]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1328]
	str.w r3, [r0, #1332]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1000]
	str.w r3, [r0, #1004]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1008]
	str.w r3, [r0, #1012]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #680]
	str.w r3, [r0, #684]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #352]
	str.w r3, [r0, #356]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #24]
	str.w r3, [r0, #28]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1992]
	str.w r3, [r0, #1996]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1664]
	str.w r3, [r0, #1668]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1336]
	str.w r3, [r0, #1340]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1344]
	str.w r3, [r0, #1348]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1016]
	str.w r3, [r0, #1020]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #688]
	str.w r3, [r0, #692]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #360]
	str.w r3, [r0, #364]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #32]
	str.w r3, [r0, #36]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2000]
	str.w r3, [r0, #2004]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1672]
	str.w r3, [r0, #1676]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1680]
	str.w r3, [r0, #1684]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1352]
	str.w r3, [r0, #1356]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1024]
	str.w r3, [r0, #1028]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #696]
	str.w r3, [r0, #700]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #368]
	str.w r3, [r0, #372]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #40]
	str.w r3, [r0, #44]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2008]
	str.w r3, [r0, #2012]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2016]
	str.w r3, [r0, #2020]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1688]
	str.w r3, [r0, #1692]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1360]
	str.w r3, [r0, #1364]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1032]
	str.w r3, [r0, #1036]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #704]
	str.w r3, [r0, #708]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #376]
	str.w r3, [r0, #380]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #48]
	str.w r3, [r0, #52]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #56]
	str.w r3, [r0, #60]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2024]
	str.w r3, [r0, #2028]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1696]
	str.w r3, [r0, #1700]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1368]
	str.w r3, [r0, #1372]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1040]
	str.w r3, [r0, #1044]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #712]
	str.w r3, [r0, #716]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #384]
	str.w r3, [r0, #388]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #392]
	str.w r3, [r0, #396]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #64]
	str.w r3, [r0, #68]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2032]
	str.w r3, [r0, #2036]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1704]
	str.w r3, [r0, #1708]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1376]
	str.w r3, [r0, #1380]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1048]
	str.w r3, [r0, #1052]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #720]
	str.w r3, [r0, #724]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #728]
	str.w r3, [r0, #732]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #400]
	str.w r3, [r0, #404]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #72]
	str.w r3, [r0, #76]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2040]
	str.w r3, [r0, #2044]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1712]
	str.w r3, [r0, #1716]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1384]
	str.w r3, [r0, #1388]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1056]
	str.w r3, [r0, #1060]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1064]
	str.w r3, [r0, #1068]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #736]
	str.w r3, [r0, #740]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #408]
	str.w r3, [r0, #412]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #80]
	str.w r3, [r0, #84]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2048]
	str.w r3, [r0, #2052]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1720]
	str.w r3, [r0, #1724]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1392]
	str.w r3, [r0, #1396]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1400]
	str.w r3, [r0, #1404]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1072]
	str.w r3, [r0, #1076]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #744]
	str.w r3, [r0, #748]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #416]
	str.w r3, [r0, #420]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #88]
	str.w r3, [r0, #92]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2056]
	str.w r3, [r0, #2060]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1728]
	str.w r3, [r0, #1732]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1736]
	str.w r3, [r0, #1740]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1408]
	str.w r3, [r0, #1412]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1080]
	str.w r3, [r0, #1084]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #752]
	str.w r3, [r0, #756]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #424]
	str.w r3, [r0, #428]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #96]
	str.w r3, [r0, #100]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2064]
	str.w r3, [r0, #2068]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2072]
	str.w r3, [r0, #2076]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1744]
	str.w r3, [r0, #1748]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1416]
	str.w r3, [r0, #1420]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1088]
	str.w r3, [r0, #1092]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #760]
	str.w r3, [r0, #764]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #432]
	str.w r3, [r0, #436]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #104]
	str.w r3, [r0, #108]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #112]
	str.w r3, [r0, #116]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2080]
	str.w r3, [r0, #2084]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1752]
	str.w r3, [r0, #1756]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1424]
	str.w r3, [r0, #1428]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1096]
	str.w r3, [r0, #1100]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #768]
	str.w r3, [r0, #772]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #440]
	str.w r3, [r0, #444]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #448]
	str.w r3, [r0, #452]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #120]
	str.w r3, [r0, #124]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2088]
	str.w r3, [r0, #2092]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1760]
	str.w r3, [r0, #1764]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1432]
	str.w r3, [r0, #1436]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1104]
	str.w r3, [r0, #1108]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #776]
	str.w r3, [r0, #780]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #784]
	str.w r3, [r0, #788]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #456]
	str.w r3, [r0, #460]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #128]
	str.w r3, [r0, #132]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2096]
	str.w r3, [r0, #2100]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1768]
	str.w r3, [r0, #1772]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1440]
	str.w r3, [r0, #1444]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1112]
	str.w r3, [r0, #1116]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1120]
	str.w r3, [r0, #1124]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #792]
	str.w r3, [r0, #796]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #464]
	str.w r3, [r0, #468]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #136]
	str.w r3, [r0, #140]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2104]
	str.w r3, [r0, #2108]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1776]
	str.w r3, [r0, #1780]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1448]
	str.w r3, [r0, #1452]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1456]
	str.w r3, [r0, #1460]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1128]
	str.w r3, [r0, #1132]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #800]
	str.w r3, [r0, #804]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #472]
	str.w r3, [r0, #476]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #144]
	str.w r3, [r0, #148]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2112]
	str.w r3, [r0, #2116]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1784]
	str.w r3, [r0, #1788]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1792]
	str.w r3, [r0, #1796]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1464]
	str.w r3, [r0, #1468]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1136]
	str.w r3, [r0, #1140]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #808]
	str.w r3, [r0, #812]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #480]
	str.w r3, [r0, #484]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #152]
	str.w r3, [r0, #156]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2120]
	str.w r3, [r0, #2124]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2128]
	str.w r3, [r0, #2132]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1800]
	str.w r3, [r0, #1804]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1472]
	str.w r3, [r0, #1476]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1144]
	str.w r3, [r0, #1148]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #816]
	str.w r3, [r0, #820]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #488]
	str.w r3, [r0, #492]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #160]
	str.w r3, [r0, #164]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #168]
	str.w r3, [r0, #172]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2136]
	str.w r3, [r0, #2140]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1808]
	str.w r3, [r0, #1812]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1480]
	str.w r3, [r0, #1484]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1152]
	str.w r3, [r0, #1156]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #824]
	str.w r3, [r0, #828]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #496]
	str.w r3, [r0, #500]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #504]
	str.w r3, [r0, #508]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #176]
	str.w r3, [r0, #180]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2144]
	str.w r3, [r0, #2148]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1816]
	str.w r3, [r0, #1820]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1488]
	str.w r3, [r0, #1492]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1160]
	str.w r3, [r0, #1164]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #832]
	str.w r3, [r0, #836]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #840]
	str.w r3, [r0, #844]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #512]
	str.w r3, [r0, #516]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #184]
	str.w r3, [r0, #188]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2152]
	str.w r3, [r0, #2156]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1824]
	str.w r3, [r0, #1828]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1496]
	str.w r3, [r0, #1500]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1168]
	str.w r3, [r0, #1172]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1176]
	str.w r3, [r0, #1180]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #848]
	str.w r3, [r0, #852]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #520]
	str.w r3, [r0, #524]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #192]
	str.w r3, [r0, #196]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2160]
	str.w r3, [r0, #2164]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1832]
	str.w r3, [r0, #1836]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1504]
	str.w r3, [r0, #1508]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1512]
	str.w r3, [r0, #1516]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1184]
	str.w r3, [r0, #1188]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #856]
	str.w r3, [r0, #860]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #528]
	str.w r3, [r0, #532]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #200]
	str.w r3, [r0, #204]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2168]
	str.w r3, [r0, #2172]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1840]
	str.w r3, [r0, #1844]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1848]
	str.w r3, [r0, #1852]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1520]
	str.w r3, [r0, #1524]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1192]
	str.w r3, [r0, #1196]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #864]
	str.w r3, [r0, #868]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #536]
	str.w r3, [r0, #540]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #208]
	str.w r3, [r0, #212]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2176]
	str.w r3, [r0, #2180]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2184]
	str.w r3, [r0, #2188]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1856]
	str.w r3, [r0, #1860]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1528]
	str.w r3, [r0, #1532]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1200]
	str.w r3, [r0, #1204]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #872]
	str.w r3, [r0, #876]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #544]
	str.w r3, [r0, #548]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #216]
	str.w r3, [r0, #220]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #224]
	str.w r3, [r0, #228]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2192]
	str.w r3, [r0, #2196]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1864]
	str.w r3, [r0, #1868]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1536]
	str.w r3, [r0, #1540]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1208]
	str.w r3, [r0, #1212]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #880]
	str.w r3, [r0, #884]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #552]
	str.w r3, [r0, #556]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #560]
	str.w r3, [r0, #564]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #232]
	str.w r3, [r0, #236]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2200]
	str.w r3, [r0, #2204]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1872]
	str.w r3, [r0, #1876]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1544]
	str.w r3, [r0, #1548]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1216]
	str.w r3, [r0, #1220]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #888]
	str.w r3, [r0, #892]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #896]
	str.w r3, [r0, #900]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #568]
	str.w r3, [r0, #572]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #240]
	str.w r3, [r0, #244]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2208]
	str.w r3, [r0, #2212]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1880]
	str.w r3, [r0, #1884]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1552]
	str.w r3, [r0, #1556]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1224]
	str.w r3, [r0, #1228]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1232]
	str.w r3, [r0, #1236]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #904]
	str.w r3, [r0, #908]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #576]
	str.w r3, [r0, #580]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #248]
	str.w r3, [r0, #252]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2216]
	str.w r3, [r0, #2220]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1888]
	str.w r3, [r0, #1892]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1560]
	str.w r3, [r0, #1564]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1568]
	str.w r3, [r0, #1572]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1240]
	str.w r3, [r0, #1244]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #912]
	str.w r3, [r0, #916]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #584]
	str.w r3, [r0, #588]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #256]
	str.w r3, [r0, #260]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2224]
	str.w r3, [r0, #2228]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1896]
	str.w r3, [r0, #1900]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1904]
	str.w r3, [r0, #1908]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1576]
	str.w r3, [r0, #1580]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1248]
	str.w r3, [r0, #1252]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #920]
	str.w r3, [r0, #924]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #592]
	str.w r3, [r0, #596]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #264]
	str.w r3, [r0, #268]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2232]
	str.w r3, [r0, #2236]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2240]
	str.w r3, [r0, #2244]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1912]
	str.w r3, [r0, #1916]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1584]
	str.w r3, [r0, #1588]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1256]
	str.w r3, [r0, #1260]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #928]
	str.w r3, [r0, #932]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #600]
	str.w r3, [r0, #604]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #272]
	str.w r3, [r0, #276]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #280]
	str.w r3, [r0, #284]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2248]
	str.w r3, [r0, #2252]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1920]
	str.w r3, [r0, #1924]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1592]
	str.w r3, [r0, #1596]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1264]
	str.w r3, [r0, #1268]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #936]
	str.w r3, [r0, #940]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #608]
	str.w r3, [r0, #612]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #616]
	str.w r3, [r0, #620]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #288]
	str.w r3, [r0, #292]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2256]
	str.w r3, [r0, #2260]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1928]
	str.w r3, [r0, #1932]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1600]
	str.w r3, [r0, #1604]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1272]
	str.w r3, [r0, #1276]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #944]
	str.w r3, [r0, #948]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #952]
	str.w r3, [r0, #956]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #624]
	str.w r3, [r0, #628]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #296]
	str.w r3, [r0, #300]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2264]
	str.w r3, [r0, #2268]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1936]
	str.w r3, [r0, #1940]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1608]
	str.w r3, [r0, #1612]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1280]
	str.w r3, [r0, #1284]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1288]
	str.w r3, [r0, #1292]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #960]
	str.w r3, [r0, #964]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #632]
	str.w r3, [r0, #636]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #304]
	str.w r3, [r0, #308]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2272]
	str.w r3, [r0, #2276]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1944]
	str.w r3, [r0, #1948]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1616]
	str.w r3, [r0, #1620]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1624]
	str.w r3, [r0, #1628]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1296]
	str.w r3, [r0, #1300]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #968]
	str.w r3, [r0, #972]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #640]
	str.w r3, [r0, #644]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #312]
	str.w r3, [r0, #316]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2280]
	str.w r3, [r0, #2284]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1952]
	str.w r3, [r0, #1956]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1960]
	str.w r3, [r0, #1964]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1632]
	str.w r3, [r0, #1636]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #1304]
	str.w r3, [r0, #1308]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #976]
	str.w r3, [r0, #980]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #648]
	str.w r3, [r0, #652]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #320]
	str.w r3, [r0, #324]
	ldr.w r3, [r1, #4]
	ldr.w r2, [r1], #8
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	smulbb r8, r10, r3
	smulbt r9, r10, r3
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r3, r8, r9, lsl #16
	str.w r2, [r0, #2288]
	str.w r3, [r0, #2292]
	pop {r4-r11, pc}

.global imask1024_1148
.type imask1024_1148, %function
imask1024_1148:
    push {r4-r9, lr}
.rept 64
    ldr.w r3, [r1, #4]
    ldr.w r4, [r1, #8]
    ldr.w r5, [r1, #12]
    ldr.w r6, [r1, #16]
    ldr.w r7, [r1, #20]
    ldr.w r8, [r1, #24]
    ldr.w r9, [r1, #28]
    ldr.w r2, [r1], #32
    str.w r3, [r0, #4]
    str.w r4, [r0, #8]
    str.w r5, [r0, #12]
    str.w r6, [r0, #16]
    str.w r7, [r0, #20]
    str.w r8, [r0, #24]
    str.w r9, [r0, #28]
    str.w r2, [r0], #32
.endr
    pop {r4-r9, pc}

.global imask1024x_1148
.type imask1024x_1148, %function
imask1024x_1148:
    push {r4-r9, lr}
    add.w r1, r1, #2
.rept 64
    ldr.w r3, [r1, #4]
    ldr.w r4, [r1, #8]
    ldr.w r5, [r1, #12]
    ldr.w r6, [r1, #16]
    ldr.w r7, [r1, #20]
    ldr.w r8, [r1, #24]
    ldr.w r9, [r1, #28]
    ldr.w r2, [r1], #32
    str.w r3, [r0, #4]
    str.w r4, [r0, #8]
    str.w r5, [r0, #12]
    str.w r6, [r0, #16]
    str.w r7, [r0, #20]
    str.w r8, [r0, #24]
    str.w r9, [r0, #28]
    str.w r2, [r0], #32
.endr
    pop {r4-r9, pc}