.p2align
.syntax unified
.text
.global good_mask_41_7_2_256
.type good_mask_41_7_2_256, %function
good_mask_41_7_2_256:
	push {r4-r11, lr}
	mov.w r2, #0
	ldr.w r3, [r1, #0]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #492]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #328]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #164]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #168]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #4]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #496]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #332]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #336]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #172]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #8]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #500]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #504]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #340]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #176]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #12]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #508]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #344]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #180]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #16]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #348]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #184]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #20]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #352]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #188]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #24]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #28]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #356]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #192]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #196]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #32]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #360]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #364]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #200]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #36]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #368]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #204]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #40]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #372]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #208]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #44]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #376]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #212]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #48]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #380]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #216]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #52]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #56]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #384]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #220]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #224]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #60]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #388]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #392]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #228]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #64]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #396]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #232]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #68]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #400]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #236]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #72]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #404]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #240]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #76]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #408]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #244]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #80]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #84]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #412]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #248]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #252]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #88]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #416]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #420]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #256]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #92]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #424]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #260]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #96]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #428]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #264]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #100]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #432]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #268]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #104]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #436]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #272]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #108]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #112]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #440]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #276]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #280]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #116]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #444]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #448]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #284]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #120]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #452]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #288]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #124]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #456]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #292]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #128]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #460]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #296]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #132]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #464]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #300]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #136]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #140]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #468]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #304]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #308]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #144]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #472]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #476]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #312]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #148]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #480]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #316]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #152]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #484]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #320]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #156]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #488]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #324]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #160]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	pop {r4-r11, pc}

.global good_mask_41_7_2_256x
.type good_mask_41_7_2_256x, %function
good_mask_41_7_2_256x:
	push {r4-r11, lr}
	mov.w r2, #0
	ldrh.w r3, [r1], #-2
    lsl.w r3, #16
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #492]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #328]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #164]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #168]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #4]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #496]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #332]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #336]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #172]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #8]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #500]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #504]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #340]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #176]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #12]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #508]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #344]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #180]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #16]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldrh.w r3, [r1, #512]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #348]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #184]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #20]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #352]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #188]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #24]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #28]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #356]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #192]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #196]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #32]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #360]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #364]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #200]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #36]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #368]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #204]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #40]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #372]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #208]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #44]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #376]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #212]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #48]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #380]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #216]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #52]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #56]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #384]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #220]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #224]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #60]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #388]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #392]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #228]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #64]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #396]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #232]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #68]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #400]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #236]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #72]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #404]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #240]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #76]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #408]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #244]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #80]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #84]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #412]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #248]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #252]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #88]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #416]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #420]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #256]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #92]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #424]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #260]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #96]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #428]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #264]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #100]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #432]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #268]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #104]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #436]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #272]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #108]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #112]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #440]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #276]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #280]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #116]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #444]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #448]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #284]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #120]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #452]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #288]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #124]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #456]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #292]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #128]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #460]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #296]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #132]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #464]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #300]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #136]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #140]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #468]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #304]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #308]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #144]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #472]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #476]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #312]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #148]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #480]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #316]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #152]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #484]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #320]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #156]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	str.w r2, [r0], #4
	ldr.w r3, [r1, #488]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #324]
	str.w r3, [r0], #4
	ldr.w r3, [r1, #160]
	str.w r3, [r0], #4
	str.w r2, [r0], #4
	pop {r4-r11, pc}

.global inv_good_mask_41_7_2_574
.type inv_good_mask_41_7_2_574, %function
inv_good_mask_41_7_2_574:
	push {r4-r11, lr}
	mov.w r10, #5149
	movw.w r11, #44798
	movt.w r11, #12
	mov.w r12, #5167
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #0]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #984]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #820]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #656]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #492]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #328]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #164]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #168]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #4]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #988]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #824]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #660]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #496]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #332]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #336]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #172]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #8]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #992]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #828]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #664]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #500]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #504]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #340]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #176]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #12]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #996]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #832]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #668]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #672]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #508]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #344]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #180]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #16]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1000]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #836]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #840]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #676]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #512]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #348]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #184]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #20]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1004]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1008]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #844]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #680]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #516]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #352]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #188]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #24]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #28]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1012]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #848]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #684]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #520]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #356]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #192]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #196]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #32]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1016]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #852]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #688]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #524]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #360]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #364]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #200]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #36]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1020]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #856]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #692]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #528]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #532]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #368]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #204]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #40]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1024]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #860]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #696]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #700]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #536]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #372]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #208]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #44]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1028]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #864]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #868]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #704]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #540]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #376]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #212]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #48]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1032]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1036]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #872]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #708]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #544]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #380]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #216]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #52]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #56]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1040]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #876]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #712]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #548]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #384]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #220]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #224]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #60]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1044]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #880]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #716]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #552]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #388]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #392]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #228]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #64]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1048]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #884]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #720]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #556]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #560]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #396]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #232]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #68]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1052]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #888]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #724]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #728]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #564]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #400]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #236]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #72]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1056]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #892]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #896]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #732]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #568]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #404]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #240]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #76]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1060]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1064]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #900]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #736]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #572]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #408]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #244]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #80]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #84]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1068]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #904]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #740]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #576]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #412]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #248]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #252]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #88]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1072]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #908]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #744]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #580]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #416]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #420]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #256]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #92]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1076]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #912]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #748]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #584]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #588]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #424]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #260]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #96]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1080]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #916]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #752]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #756]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #592]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #428]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #264]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #100]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1084]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #920]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #924]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #760]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #596]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #432]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #268]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #104]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1088]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1092]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #928]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #764]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #600]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #436]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #272]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #108]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #112]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1096]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #932]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #768]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #604]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #440]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #276]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #280]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #116]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1100]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #936]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #772]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #608]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #444]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #448]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #284]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #120]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1104]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #940]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #776]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #612]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #616]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #452]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #288]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #124]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1108]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #944]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #780]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #784]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #620]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #456]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #292]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #128]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1112]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #948]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #952]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #788]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #624]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #460]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #296]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #132]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1116]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1120]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #956]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #792]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #628]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #464]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #300]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #136]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #140]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1124]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #960]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #796]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #632]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #468]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #304]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #308]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #144]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1128]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #964]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #800]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #636]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #472]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #476]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #312]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #148]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1132]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #968]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #804]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #640]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #644]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #480]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #316]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #152]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1136]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #972]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #808]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #812]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #648]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #484]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #320]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #156]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1140]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #976]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #980]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #816]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #652]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #488]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #324]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #160]
	ldr.w r2, [r1], #4
	smulbb r8, r10, r2
	smulbt r9, r10, r2
	smmulr lr, r8, r11
	mls r8, lr, r12, r8
	smmulr lr, r9, r11
	mls r9, lr, r12, r9
	pkhbt r2, r8, r9, lsl #16
	str.w r2, [r0, #1144]
	pop {r4-r11, pc}

.global imask512_574
.type imask512_574, %function
imask512_574:
    push {r4-r9, lr}
.rept 32
    ldr.w r3, [r1, #4]
    ldr.w r4, [r1, #8]
    ldr.w r5, [r1, #12]
    ldr.w r6, [r1, #16]
    ldr.w r7, [r1, #20]
    ldr.w r8, [r1, #24]
    ldr.w r9, [r1, #28]
    ldr.w r2, [r1], #32
    str.w r3, [r0, #4]
    str.w r4, [r0, #8]
    str.w r5, [r0, #12]
    str.w r6, [r0, #16]
    str.w r7, [r0, #20]
    str.w r8, [r0, #24]
    str.w r9, [r0, #28]
    str.w r2, [r0], #32
.endr
    pop {r4-r9, pc}

.global imask512x_574
.type imask512x_574, %function
imask512x_574:
    push {r4-r9, lr}
    add.w r1, r1, #2
.rept 32
    ldr.w r3, [r1, #4]
    ldr.w r4, [r1, #8]
    ldr.w r5, [r1, #12]
    ldr.w r6, [r1, #16]
    ldr.w r7, [r1, #20]
    ldr.w r8, [r1, #24]
    ldr.w r9, [r1, #28]
    ldr.w r2, [r1], #32
    str.w r3, [r0, #4]
    str.w r4, [r0, #8]
    str.w r5, [r0, #12]
    str.w r6, [r0, #16]
    str.w r7, [r0, #20]
    str.w r8, [r0, #24]
    str.w r9, [r0, #28]
    str.w r2, [r0], #32
.endr
    pop {r4-r9, pc}