.p2align 2,,3
.syntax unified
.text
wpad:
	.word 1038337
	.word -103819265
@ =78=
	.word 405464
	.word 405464
	.word -94414
	.word -94414
	.word -490416
	.word 150027
	.word -490416
	.word 411551
	.word 442856
	.word 150027
	.word 382994
	.word 195965
	.word 411551
	.word 237083
	.word -103099
	.word 442856
	.word 227096
	.word 301420
	.word 382994
	.word -479116
	.word -235832
	.word 195965
	.word 35593
	.word 489231
	.word 237083
	.word -68896
	.word -511761
	.word -103099
	.word -153477
	.word 302769
	.word 227096
	.word -141491
	.word -51198
	.word 301420
	.word -139179
	.word -113238
	.word -479116
	.word -44792
	.word -238793
	.word -235832
	.word -321266
	.word 130891
	.word 35593
	.word -233657
	.word 453088
	.word 489231
	.word 6572
	.word -499710
	.word -68896
	.word -11188
	.word 242732
	.word -511761
	.word 291027
	.word 306882
	.word -153477
	.word -181223
	.word -414992
	.word 302769
	.word -499631
	.word 124244
	.word -141491
	.word 298006
	.word -110335
	.word -51198
	.word 390196
	.word 318879
	.word -139179
	.word -415263
	.word -149234
	.word -113238
	.word 496122
	.word -414520
	.word -44792
	.word 105114
	.word -474481
	.word -238793
	.word -495553
	.word -470221
	.word -321266
	.word -498588
	.word 24399
	.word 130891
	.word 261084
	.word 143890
	.word -233657
	.word 149602
	.word -292202
	.word 453088
	.word 166245
	.word -5855
	.word 6572
	.word 353444
	.word 263149
	.word -499710
	.word 125854
	.word 129478
	.word -11188
	.word 387087
	.word -334231
	.word 242732
	.word -357539
	.word -156857
	.word 291027
	.word -130483
	.word -26821
	.word 306882
	.word 153970
	.word 355867
	.word -181223
	.word 75992
	.word -27160
	.word -414992
	.word 128894
	.word -343719
	.word -499631
	.word 216710
	.word 242388
	.word 124244
	.word -245930
	.word 200377
	.word 298006
	.word -396104
	.word -296873
	.word -110335
	.word 225037
	.word -6208
	.word 390196
	.word -105134
	.word 388789
	.word 318879
	.word -247134
	.word 441071
	.word -415263
	.word 304327
	.word 183527
	.word -149234
	.word -118825
	.word -332465
	.word 496122
	.word -297191
	.word 487273
	.word -414520
	.word -497058
	.word 349815
	.word 105114
	.word 485952
	.word -378748
	.word -474481
	.word -370074
	.word 129206
	.word -495553
	.word 445308
	.word 126253
	.word -470221
	.word 291070
	.word 75785
	.word -498588
	.word 473158
	.word 43608
	.word 24399
	.word -220103
	.word 172017
	.word 261084
	.word -817
	.word 237495
	.word 143890
	.word 136427
	.word 366728
	.word 149602
	.word 198016
	.word 305692
	.word -292202
	.word -99517
	.word -49366
	.word 166245
	.word -24490
	.word -57817
	.word -5855
	.word -356188
	.word -390717
	.word 353444
	.word -313990
	.word 363198
	.word 263149
	.word 190785
	.word 266192
	.word 125854
	.word 467076
	.word -472239
	.word 129478
	.word 390080
	.word -385802
	.word 387087
	.word 90564
	.word -515191
	.word -334231
	.word -345937
	.word 128231
	.word -357539
	.word 372932
	.word 279139
	.word -156857
	.word -336157
	.word 498139
	.word -130483
	.word 246484
	.word -111050
	.word -26821
	.word -125197
	.word -14172
	.word 153970
	.word 232330
	.word -324065
	.word 355867
	.word 400571
	.word 123113
	.word 75992
	.word -85761
	.word -87950
	.word -27160
	.word 471674
	.word 122951
	.word 128894
	.word 476195
	.word -27108
	.word -343719
	.word 53104
	.word -74072
	.word 216710
	.word 360808
	.word 457166
	.word 242388
	.word 292909
	.word 479138
	.word -245930
	.word -453968
	.word 149243
	.word 200377
	.word 9929
	.word -237691
	.word -396104
	.word -332891
	.word 162592
	.word -296873
	.word -237004
	.word 233915
	.word 225037
	.word -388970
	.word -49977
	.word -6208
	.word -361281
	.word 8227
	.word -105134
	.word 516270
	.word 352632
	.word 388789
	.word 15675
	.word -330800
	.word -247134
	.word 97970
	.word 274114
	.word 441071
	.word 238590
	.word -499231
	.word 304327
	.word -517724
	.word -144751
	.word 183527
	.word -326997
	.word 288269
	.word -118825
	.word -152891
	.word -93799
	.word -332465
	.word 170727
	.word -115346
	.word -297191
	.word -61214
	.word -408913
	.word 487273
	.word 504428
	.word 77577
	.word -497058
	.word -254090
	.word -496838
	.word 349815
	.word 420496
	.word 350134
	.word 485952
	.word -417344
	.word 71879
	.word -378748
	.word -410774
	.word 186602
	.word -370074
	.word 118064
	.word -20772
	.word 129206
	.word 163417
	.word -285662
	.word 445308
	.word 353696
	.word -318471
	.word 126253
	.word -484325
	.word 496768
	.word 291070
	.word -332693
	.word -442729
	.word 75785
	.word -48928
	.word -515837
	.word 473158
	.word -499215
	.word 37631
	.word 43608
	.word -334490
	.word -250794
	.word -220103
	.word 325573
	.word 48150
	.word 172017
	.word 428291
	.word -516530
	.word -817
	.word -172040
	.word 96686
	.word 237495
	.word 293987
	.word -509083
	.word 136427
	.word -214060
	.word -309905
	.word 366728
	.word -509226
	.word -491350
	.word 198016
	.word -385684
	.word -299832
	.word 305692
	.word -134737
	.word -394113
	.word -99517
	.word 162768
	.word 256311
	.word -49366
	.word -291131
	.word 493524
	.word -24490
	.word 361258
	.word 308562
	.word -57817
	.word -129194
	.word 96676
	.word -356188
	.word -9924
	.word 259114
	.word -390717
	.word 296013
	.word 72488
	.word -313990
	.word -200098
	.word -296531
	.word 363198
	.word -273428
	.word 129862
	.word 190785
	.word -105569
	.word -436675
	.word 266192
	.word 472400
	.word 326227
	.word 467076
	.word 213529
	.word -96211
	.word -472239
	.word -467131
	.word 236586
	.word 390080
	.word 386512
	.word 317135
	.word -385802
	.word 354871
	.word -475751
@ =56=
	.word 405464
	.word 405464
	.word -94414
	.word -94414
	.word -490416
	.word 150027
	.word -490416
	.word 411551
	.word 442856
	.word 150027
	.word 382994
	.word 195965
	.word 411551
	.word 237083
	.word -103099
	.word 442856
	.word 227096
	.word 301420
	.word 382994
	.word -479116
	.word -235832
	.word 195965
	.word 35593
	.word 489231
	.word 237083
	.word -68896
	.word -511761
	.word -103099
	.word -153477
	.word 302769
	.word 227096
	.word -141491
	.word -51198
	.word 301420
	.word -139179
	.word -113238
	.word -479116
	.word -44792
	.word -238793
	.word -235832
	.word -321266
	.word 130891
	.word 35593
	.word -233657
	.word 453088
	.word 489231
	.word 6572
	.word -499710
	.word -68896
	.word -11188
	.word 242732
	.word -511761
	.word 291027
	.word 306882
	.word -153477
	.word -181223
	.word -414992
	.word 302769
	.word -499631
	.word 124244
	.word -141491
	.word 298006
	.word -110335
	.word -51198
	.word 390196
	.word 318879
	.word -139179
	.word -415263
	.word -149234
	.word -113238
	.word 496122
	.word -414520
	.word -44792
	.word 105114
	.word -474481
	.word -238793
	.word -495553
	.word -470221
	.word -321266
	.word -498588
	.word 24399
	.word 130891
	.word 261084
	.word 143890
	.word -233657
	.word 149602
	.word -292202
	.word 453088
	.word 166245
	.word -5855
	.word 6572
	.word 353444
	.word 263149
	.word -499710
	.word 125854
	.word 129478
@ =34=
	.word 405464
	.word 405464
	.word -94414
	.word -94414
	.word -490416
	.word 150027
	.word -490416
	.word 411551
	.word 442856
	.word 150027
	.word 382994
	.word 195965
	.word 411551
	.word 237083
	.word -103099
	.word 442856
	.word 227096
	.word 301420
	.word 382994
	.word -479116
	.word -235832
	.word 195965
	.word 35593
	.word 489231
@ =012=
	.word -94414
	.word -490416
	.word 150027
// void intt1024_32bit (int *v);
.global intt1024_32bit
.type intt1024_32bit, %function
intt1024_32bit:
	push {r4-r11, lr}
	adr.w r1, wpad
	ldm r1!, {r11-r12}
	vmov.w s0, s1, r0, r1
	add.w lr, r0, #4096
	vmov s2, lr @ lr: flag(r0-end)
	vmov r0, s0
intt2_layer_7_8:
	vmov r10, s1
	ldm r10!, {r1-r3}
	vmov s1, r10
	ldr.w r4, [r0]
	ldr.w r5, [r0, #8]
	ldr.w r6, [r0, #16]
	ldr.w r7, [r0, #24]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #8]
	str.w r6, [r0, #16]
	str.w r7, [r0, #24]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #8]
	ldr.w r6, [r0, #16]
	ldr.w r7, [r0, #24]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #8]
	str.w r6, [r0, #16]
	str.w r7, [r0, #24]
	str.w r4, [r0], #28
	cmp.w r0, lr
	bne.w intt2_layer_7_8
	vmov r0, s0
intt2_layer_5_6:
	vmov r10, s1
	ldm r10!, {r1-r3}
	vmov s1, r10
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #32]
	ldr.w r6, [r0, #64]
	ldr.w r7, [r0, #96]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #32]
	str.w r6, [r0, #64]
	str.w r7, [r0, #96]
	str.w r4, [r0], #100
	cmp.w r0, lr
	bne.w intt2_layer_5_6
	vmov r0, s0
intt2_layer_3_4:
	vmov r10, s1
	ldm r10!, {r1-r3}
	vmov s1, r10
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0], #4
	ldr.w r4, [r0]
	ldr.w r5, [r0, #128]
	ldr.w r6, [r0, #256]
	ldr.w r7, [r0, #384]
	sub.w r10, r4, r5
	add.w r4, r4, r5
	smull r8, r5, r10, r2
	mul.w r9, r8, r12
	smlal r8, r5, r9, r11
	sub.w r10, r6, r7
	add.w r6, r6, r7
	smull r8, r7, r10, r3
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	sub.w r10, r4, r6
	add.w r4, r4, r6
	smull r8, r6, r10, r1
	mul.w r9, r8, r12
	smlal r8, r6, r9, r11
	sub.w r10, r5, r7
	add.w r5, r5, r7
	smull r8, r7, r10, r1
	mul.w r9, r8, r12
	smlal r8, r7, r9, r11
	str.w r5, [r0, #128]
	str.w r6, [r0, #256]
	str.w r7, [r0, #384]
	str.w r4, [r0]
	add.w r0, #388
	cmp.w r0, lr
	bne.w intt2_layer_3_4
	vmov r0, s0
	vmov r10, s1
	ldm r10!, {r1-r3}
	vmov s1, r10
	vmov s4, s5, r1, r2
	vmov s6, r3
	add.w lr, r0, #512 @ 128
intt2_layer_0_1_2:
	vmov r1, r2, s4, s5
	vmov r3, s6
	ldr.w r7, [r0, #2048]
	ldr.w r8, [r0, #2560]
	ldr.w r9, [r0, #3072]
	ldr.w r10, [r0, #3584]
	sub.w r6, r7, r8
	add.w r7, r7, r8
	smull r4, r8, r6, r2
	mul.w r5, r4, r12
	smlal r4, r8, r5, r11
	sub.w r6, r9, r10
	add.w r9, r9, r10
	smull r4, r10, r6, r3
	mul.w r5, r4, r12
	smlal r4, r10, r5, r11
	sub.w r6, r7, r9
	add.w r7, r7, r9
	smull r4, r9, r6, r1
	mul.w r5, r4, r12
	smlal r4, r9, r5, r11
	sub.w r6, r8, r10
	add.w r8, r8, r10
	smull r4, r10, r6, r1
	mul.w r5, r4, r12
	smlal r4, r10, r5, r11
	ldr.w r3, [r0]
	ldr.w r4, [r0, #512]
	ldr.w r5, [r0, #1024]
	ldr.w r6, [r0, #1536]
	add.w r3, r3, r4
	sub.w r4, r3, r4, lsl #1
	sub.w r2, r5, r6
	add.w r5, r5, r6
	smull r1, r6, r2, r1
	mul.w r2, r1, r12
	smlal r1, r6, r2, r11
	add.w r3, r3, r5
	sub.w r5, r3, r5, lsl #1
	add.w r4, r4, r6
	sub.w r6, r4, r6, lsl #1
	@ layer 0
	add.w r3, r3, r7
	sub.w r7, r3, r7, lsl #1
	add.w r4, r4, r8
	sub.w r8, r4, r8, lsl #1
	add.w r5, r5, r9
	sub.w r9, r5, r9, lsl #1
	add.w r6, r6, r10
	sub.w r10, r6, r10, lsl #1
	str.w r4, [r0, #512]
	str.w r5, [r0, #1024]
	str.w r6, [r0, #1536]
	str.w r7, [r0, #2048]
	str.w r8, [r0, #2560]
	str.w r9, [r0, #3072]
	str.w r10, [r0, #3584]
	str.w r3, [r0], #4
	cmp.w r0, lr
	bne.w intt2_layer_0_1_2
	pop {r4-r11, pc}
