#include "poly7_macro.S"
.align
.syntax unified
.text
wpad:
    .word 470404551
    .word 943
    .word 6234
    .word 1329
    .word 5848
    .word 5244
    .word 1933
    .word 5465
    .word 1712
    .word 2746
    .word 4431
    .word 5963
    .word 1214
    .word 6518
    .word 659
    .word 4102
    .word 3075
    .word 4404
    .word 2773
    .word 5575
    .word 1602
    .word 1034
    .word 6143
    .word 719
    .word 6458
    .word 1733
    .word 5444
    .word 3447
    .word 3730
    .word 5436
    .word 1741
    .word 2364
    .word 4813
    .word 2748
    .word 4429
    .word 2716
    .word 4461
    .word 2503
    .word 4674
    .word 2150
    .word 5027
    .word 1297
    .word 5880
    .word 770
    .word 6407
    .word 5112
    .word 2065
    .word 4457
    .word 2720
    .word 72
    .word 7105
    .word 5117
    .word 2060
    .word 6177
    .word 1000
    .word 1498
    .word 5679
    .word 2980
    .word 4197
    .word 6445
    .word 732
    .word 3268
    .word 3909
    .word 5382
    .word 1795
    .word 6912
    .word 265
    .word 3196
    .word 3981
    .word 4478
    .word 2699
    .word 268
    .word 6909
    .word 1175
    .word 6002
    .word 5058
    .word 2119
    .word 6009
    .word 1168
    .word 1520
    .word 5657
    .word 1184
    .word 5993
    .word 1212
    .word 5965
    .word 5884
    .word 1293
    .word 7090
    .word 87
    .word 5145
    .word 2032
    .word 4709
    .word 2468
    .word 2704
    .word 4473
    .word 2380
    .word 4797
    .word 7114
    .word 63
    .word 5391
    .word 1786
    .word 875
    .word 6302
    .word 4072
    .word 3105
    .word 981
    .word 6196
    .word 4229
    .word 2948
    .word 729
    .word 6448
    .word 4262
    .word 2915
    .word 1129
    .word 6048
    .word 792
    .word 6385
    .word 5053
    .word 2124
    .word 3354
    .word 3823
    .word 7046
    .word 131
    .word 957
    .word 6220
    .word 1022
    .word 6155
    .word 5847
    .word 1330
    .word 6141
    .word 1036
    .word 2528
    .word 4649
    .word 5617
    .word 1560
    .word 6356
    .word 821
    .word 1778
    .word 5399
    .word 5748
    .word 1429
    .word 4811
    .word 2366
    .word 1506
    .word 5671
    .word 6335
    .word 842
    .word 3357
    .word 3820
    .word 3720
    .word 3457
    .word 3614
    .word 3563
    .word 1833
    .word 5344
    .word 6168
    .word 1009
    .word 5642
    .word 1535
    .word 5242
    .word 1935
    .word 5292
    .word 1885
    .word 6484
    .word 693
    .word 5447
    .word 1730
    .word 2448
    .word 4729
    .word 2806
    .word 4371
    .word 1854
    .word 5323
    .word 900
    .word 6277
    .word 2958
    .word 4219
    .word 4495
    .word 2682
    .word 4965
    .word 2212
    .word 1365
    .word 5812
    .word 5204
    .word 1973
    .word 3827
    .word 3350
    .word 5736
    .word 1441
    .word 276
    .word 6901
    .word 4065
    .word 3112
    .word 2531
    .word 4646
    .word 6931
    .word 246
    .word 3922
    .word 3255
    .word 5809
    .word 1368
    .word 4676
    .word 2501
    .word 1780
    .word 5397
    .word 446
    .word 6731
    .word 796
    .word 6381
    .word 6135
    .word 1042
    .word 5092
    .word 2085
    .word 3308
    .word 3869
    .word 5035
    .word 2142
    .word 6516
    .word 661
    .word 172
    .word 7005
    .word 2801
    .word 4376
    .word 6383
    .word 794
    .word 4141
    .word 3036
    .word 5524
    .word 1653
    .word 1497
    .word 5680
    .word 6212
    .word 965
    .word 1137
    .word 6040
    .word 2158
    .word 5019
    .word 3347
    .word 3830
    .word 2723
    .word 4454
    .word 2271
    .word 4906
    .word 5598
    .word 1579
    .word 1951
    .word 5226
    .word 1197
    .word 5980
    .word 6674
    .word 503
    .word 2031
    .word 5146
    .word 1404
    .word 5773
    .word 2892
    .word 4285
    .word 2706
    .word 4471
    .word 6310
    .word 867
    .word 694
    .word 6483
    .word 80
    .word 7097
    .word 5064
    .word 2113
    .word 3438
    .word 3739
    .word 3829
    .word 3348
    .word 2489
    .word 4688
    .word 6245
    .word 932
    .word 5932
    .word 1245
    .word 4970
    .word 2207
    .word 5330
    .word 1847
    .word 5285
    .word 1892
    .word 7083
    .word 94
    .word 1557
    .word 5620
    .word 2103
    .word 5074
    .word 6087
    .word 1090
    .word 4073
    .word 3104
    .word 6367
    .word 810
    .word 1644
    .word 5533
    .word 6720
    .word 457
    .word 6297
    .word 880
    .word 2360
    .word 4817
    .word 1058
    .word 6119
    .word 3015
    .word 4162
    .word 3450
    .word 3727
    .word 1187
    .word 5990
    .word 7107
    .word 70

.equ basesize, 7
.global basemul_7x7_312
.type basemul_7x7_312, %function
basemul_7x7_312:
    push {r4-r11, lr}
    adr.w lr, wpad
    ldr.w r12, [lr], #4
    add.w r11, r0, #156*basesize*2
    add.w r11, r11, #156*basesize*2
    vmov s3, s4, r11, lr
basemul_7x7_312_body:
    vmov lr, s4
    ldr.w r11, [lr], #4
    vmov s4, lr
    ldr.w r4, [r1, #4]
    ldr.w r5, [r1, #8]
    ldrh.w r6, [r1, #12]
    ldr.w r3, [r1], #14
    ldr.w r8, [r2, #4]
    ldr.w r9, [r2, #8]
    ldrh.w r10, [r2, #12]
    ldr.w r7, [r2], #14
    vmov s1, s2, r1, r2

    polymul_7x7_c6 r1, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r1, r12, lr @ c6/R
    asr.w r1, #16
    strh.w r1, [r0, #12]

    polymul_7x7_c12 r1, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r1, r12, lr
    polymul_7x7_c5 r2, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r1, r11, r1, r2
    montgomery_reduce r1, r12, lr @ c5/R

    polymul_7x7_c11 r2, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r2, r12, lr
    polymul_7x7_c4 lr, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r2, r11, r2, lr
    montgomery_reduce r2, r12, lr @ c4/R

    pkhtb r1, r1, r2, asr #16 @ c4/R c5/R
    str.w r1, [r0, #8]

    polymul_7x7_c10 r1, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r1, r12, lr
    polymul_7x7_c3 r2, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r1, r11, r1, r2
    montgomery_reduce r1, r12, lr @ c3/R

    polymul_7x7_c9 r2, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r2, r12, lr
    polymul_7x7_c2 lr, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r2, r11, r2, lr
    montgomery_reduce r2, r12, lr @ c2/R

    pkhtb r1, r1, r2, asr #16 @ c2/R c3/R
    str.w r1, [r0, #4]

    polymul_7x7_c8 r1, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r1, r12, lr
    polymul_7x7_c1 r2, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r1, r11, r1, r2
    montgomery_reduce r1, r12, lr @ c1/R

    polymul_7x7_c7 r2, r3, r4, r5, r6, r7, r8, r9, r10
    montgomery_reduce r2, r12, lr
    polymul_7x7_c0 lr, r3, r4, r5, r6, r7, r8, r9, r10
    smlabt r2, r11, r2, lr
    montgomery_reduce r2, r12, lr @ c0/R

    pkhtb r1, r1, r2, asr #16 @ c0/R c1/R
    str.w r1, [r0], #14
    
    vmov r1, r2, s1, s2
    vmov r11, s3
    cmp.w r0, r11
    bne.w basemul_7x7_312_body
    pop {r4-r11, pc}
