name: cw308t-stm32f415 build
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.10.0
        with:
          release: 14.2.Rel1
      - name: Build All (cw308t-stm32f415)
        run: make PLATFORM=cw308t-stm32f415 -j2